
language: ruby

cache: bundler

branches:
  only:
    - gh-pages

script: 
  - bundle exec jekyll algolia push
  - jekyll build && htmlproofer ./_site --disable-external --empty-alt-ignore

rvm:
 - 2.2.2
 