
title: Way of the Developer
tagline: how I become a developer

# Authors documented under _data

# GitHub related
github-repository: way-of-the-developer
github-branch: gh-pages

# Change to true for Disqus comments
disqus:
  comments: false
  disqus-shortname: 'way-of-the-developer'

google-tracking-id: 'UA-34247146-3'

# Donations with PayPal
donate-paypal: 49ZMF7YEPCR34
# Donations with BitCoins
donate-blockchain: 1P4w32KT7NwjfGLmnr1eeWs2xJs468PKSk

# Username for Keybase
keybase-username: gfarfanb

menu:
- {name: 'About', url: 'about.html'}
- {name: 'Blog', leafs: [
    {name: 'Tags', url: 'blog/tag.html'}, 
    {name: 'Categories', url: 'blog/category.html'},
    {name: 'Trace', url: 'blog/trace.html'}
  ]}
- {name: 'Contact', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://www.github.com/gfarfanb', head: true}
- {icon: 'twitter', link: 'https://twitter.com/gfarfanb', head: false}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/gfarfanb/', head: false}
- {icon: 'facebook', link: 'https://facebook.com/gfarfanb.dev', head: false}
- {icon: 'stack-overflow', link: 'https://stackoverflow.com/users/5133929/gfarfanb', head: false}
- {icon: 'envelope', link: 'mailto:gfarfanb@gmail.com', head: true}
- {icon: 'rss', link: '/feed.xml', head: true}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
